### ISSUE TITLE
Block Warning when opening Mip_Balance_Demo in Simulink

### ISSUE THREAD

**Issue by JLouis47** [ktalke12/Matlab_MiP#1]
The warning reads "The System object name beagleboneblue.fccr_bbblueIMU cannot be found.  
Copied "fccr_bbblue_driver.h" to location/include.
Copied "fccr_imu.c" to location/src.

Where can this file be located and what is it's extension?

Thank you!
![Model_Load_Warning](https://user-images.githubusercontent.com/49067363/63544672-51307680-c4eb-11e9-9560-9d36b1929c95.jpg)

**Comment by ktalke12** [comment]
Please follow instruction step 5) -1)

The file is in the +BeagleBone folder 

-Kurt

**Comment by JLouis47** [comment]
I must be doing something wrong in step #5.  Would you be able to go into more detail regarding the system object that i am missing?  It is nowhere in :ProgramData\MATLAB\SupportPackages\R2019a\toolbox\target\supportpackages\beagleboneblue 
I am looking forward to using Simulink with my EduMIP!  Your help is appreciated.
![Missing_System_Object](https://user-images.githubusercontent.com/49067363/63786546-e2bb3200-c8b7-11e9-88d2-3c023802638e.jpg)

**Comment by ktalke12** [comment]
Did you move the files from the “+BeagleBoneblue” folder like in the instructions?

Basically, it can’t find the IMU S-block, which is defined by the m-file in that folder.

-K

**Comment by JLouis47** [comment]
OK.  I copied ‘fccr_bbblueIMU.m’ to my +beagleboneblue folder, and it worked!  See attached.
Thank you so much Kurt!
![FOUND_System_Object](https://user-images.githubusercontent.com/49067363/63812386-dce14300-c8ef-11e9-9598-be3339030eab.jpg)

**Comment by ktalke12** [comment]
Fantastic!

Alternately, if you install the latest matlab BeagleBoneBlue support package, you can replace that block with the Matlab released block, as this IMU block was just for experimental demonstration.

-Kurt

**Comment by JLouis47** [comment]
Got it.  You mean this block, right? :

[cid:image003.jpg@01D55CFD.7C42C6D0]

Jim
